### PR TITLE
Fix lookup indexes handling

### PR DESCRIPTION
**Pull request by benbp**
Resolves https://github.com/RackHD/RackHD/issues/129

The first commit just contains some incremental improvements including creating the right index structure. The second commit (3136f93) contains the actual fix to https://github.com/RackHD/RackHD/issues/129

Requires: https://github.com/RackHD/RackHD/pull/133
@RackHD/corecommitters @zyoung51 @tldavies

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by zyoung51** [comment]
+1

**Comment by benbp** [comment]
Adding https://github.com/RackHD/RackHD/pull/133 as a PR dependency.

**Comment by DavidjohnBlodgett** [comment]
@benbp I assume we dont care that Jenkins is broke? otherwise :+1:

**Comment by benbp** [comment]
@DavidjohnBlodgett I linked an update to a test PR that will that side of the breakage.

**Comment by benbp** [comment]
Passing locally with the integration test update at https://github.com/RackHD/RackHD/pull/133.

**Comment by anhou** [comment]
merge this PR to let Jenkins pass

**Pull request merged**
