### PR TITLE
notification API design refactor

### PR DESCRIPTION
**Pull request by cgx027**
This PR is depended by https://github.com/RackHD/on-http/pull/410

### CODE REVIEW

**Comment by cgx027** [comment]
Remove WIP flag

**Comment by cgx027** [comment]
@RackHD/corecommitters @yyscamper @anhou @WangWinson

**Comment by cgx027** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by WangWinson** [comment]
:+1:

**Comment by yyscamper** [comment]
There is dependency PR, so the Jenkins will never success, I have to force merge this PR.

**Pull request merged**
