### PR TITLE
Ssh settings

### PR DESCRIPTION
**Pull request by VulpesArtificem**
supports https://github.com/RackHD/on-tasks/pull/150 and https://github.com/RackHD/on-tasks/pull/163 by adding optional sshSettings to node schema
@benbp

### CODE REVIEW

**Comment by anhou** [comment]
:+1:

**Comment by heckj** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
@VulpesArtificem  for sshSettings, it also need serializable like other settings? https://github.com/RackHD/on-http/blob/master/lib/serializables/v1/node.js

**Comment by benbp** [comment]
@anhou he's been using my branch for the ssh settings serializable, just put a PR up here: https://github.com/RackHD/on-http/pull/237

**Comment by anhou** [comment]
@benbp Thanks for this info, and let Jenkins test this please

**Comment by benbp** [comment]
test this please

**Pull request merged**
