### PR TITLE
Build status

### PR DESCRIPTION
**Pull request by heckj**
This should be good... except that the Node4 based build is being a little (*^*&#%*&@!%#@ and periodically failing with indeterminate errors...

### CODE REVIEW

**Comment by benbp** [comment]
@heckj still WIP or no?

**Comment by heckj** [comment]
@benbp sorry, not WIP any longer

**Comment by benbp** [comment]
:+1: 

@tldavies

**Comment by VulpesArtificem** [comment]
:+1:

**Pull request merged**
