### PR TITLE
Do not fail service startup if AMQP is not immediately available

### PR DESCRIPTION
**Pull request by benbp**
Instead, try to reconnect a bunch of times, and only fail if we exceed the maximum attempts.

https://www.pivotaltracker.com/story/show/111023884

resolves https://github.com/RackHD/RackHD/issues/59

### CODE REVIEW

**Comment by benbp** [comment]
@heckj @RackHD/corecommitters @VulpesArtificem

**Comment by heckj** [comment]
@kacole FYI

**Comment by heckj** [comment]
:+1:

**Comment by kacole2** [comment]
awesome. i'll check it out in a bit

**Comment by jlongever** [comment]
+1

**Pull request merged**
