### PR TITLE
Constants for list static files

### PR DESCRIPTION
**Pull request by lacarb**
Required for https://github.com/RackHD/on-http/pull/373

Added the following values to constants.js
```
HttpStatic: {
    onhttpStaticHttp: 'static/http',
    onhttpSkupack: 'skupack.d'
}
```

### CODE REVIEW

**Comment by yyscamper** [comment]
Personally, The constant `HttpStatic.onhttpStaticHttp` seems a little opaque to me, how about the following?
```
HttpStaticDir: {
    default: 'static/http',
    skupack: 'skupack.d'
}
```

**Comment by yyscamper** [comment]
Beside the `/static/http` and `skupack.d`, we also have following static file folder:
- upnp: https://github.com/RackHD/on-http/blob/master/lib/services/http-service.js#L213
- user defined static folder: https://github.com/RackHD/on-http/blob/master/lib/services/http-service.js#L218

Meanwhile, could you please change following string to the constant as well? So that our code will not diverge
- https://github.com/RackHD/on-http/blob/master/lib/services/http-service.js#L212
- https://github.com/RackHD/on-http/blob/master/lib/services/http-service.js#L213
- https://github.com/RackHD/on-http/blob/master/app.js#L54

**Comment by lacarb** [comment]
@yyscamper I like the name change to HttpStaticDir
I'll add upnp to constants.js
Are you suggesting that '/opt/monorail/static/http' be added as well? I hesitate as it is already represented in config.json.
I'll update the files you listed. Thanks for bringing them to my attention.

**Comment by benbp** [comment]
@lacarb I think in regards to '/opt/monorail/static/http' @yyscamper means to just make the default value a constant (which is used only if NOT defined in the config).

**Comment by benbp** [comment]
test this please

**Comment by yyscamper** [comment]
Yes, my meaning is exactly what @benbp explained. Since we have changed some of static folders to use Constant, why not change them all? so that they are all managed in the same way and avoid the divergence.

Below is my suggestion (you may have better naming)

```javascript
HttpStaticDir: {
    default: 'static/http',
    userDefault: '/opt/monorail/static/http',
    skupack: 'skupack.d',
    upnp: 'static/upnp'
}
```

```javascript
configuration.get('httpStaticRoot', Constants.HttpStaticDir.userDefault)
```

**Comment by lacarb** [comment]
@yyscamper @benbp 
Changed to 
```
HttpStaticDir: {
    systemDefault: 'static/http',
    userDefault: '/opt/monorail/static/http',
    skupack: 'skupack.d',
    upnp: './static/upnp'
}
```
I added the use of them to the files Felix mentioned. `npm test` results before and after are consistent.
Those will be added to my other pr and merged with that.

**Comment by yyscamper** [comment]
Thanks @lacarb , :+1:

**Comment by changev** [comment]
test this please

**Comment by yyscamper** [comment]
@lacarb : you need to rebase your branch to make sure the Jenkins passes.

**Comment by changev** [comment]
retest this please

**Comment by changev** [comment]
retest this please

**Comment by changev** [comment]
retest this please

**Comment by changev** [comment]
test this please

**Comment by blacara** [comment]
@yyscamper @benbp @brianparry @anhou 
Please review and rate as appropriate.

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
