### PR TITLE
hound config update

### PR DESCRIPTION
**Pull request by heckj**
# WIP

Updating hound configuration file, per https://houndci.com/configuration

### CODE REVIEW

**Comment by heckj** [comment]
. @anhou this the update needed?

**Comment by yyscamper** [comment]
I tested in my forked branch, seems this still doesn't work well.

**Comment by heckj** [comment]
thanks @yyscamper I'll do a bit more digging when I have a chance today, will make this a WIP PR to see what I can wrangle

**Comment by cgx027** [comment]
Hi @heckj , I had tested this same change in on-http and it worked. 

Hence :+1:

**Comment by yyscamper** [comment]
@heckj : Sorry, @cgx027 helps to verify your fix is correct , my testing was wrong.

**Comment by cgx027** [comment]
Just realize this PR has been closed. I created a new PR with the same purpose: https://github.com/RackHD/on-core/pull/201

**Pull request closed without merging**
