### PR TITLE
Add support for using PostgreSQL as an alternative backend

### PR DESCRIPTION
**Pull request by zyoung51**
- this commit adds support for non-workflow related models only

### CODE REVIEW

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
:+1:

**Comment by zyoung51** [comment]
jenkins: test this please

**Comment by jlongever** [comment]
looks like the setup() method for redfish compose tests didn't delete the composed systems from the previous test run.  Not sure why, no error in setup().. I manually deleted them.  jenkins, test this please.

**Comment by zyoung51** [comment]
test this please

**Pull request merged**
