### PR TITLE
Added supported obm setting in constants

### PR DESCRIPTION
**Pull request by iceiilin**
Added supported obm setting in constants

https://hwjiraprd01.corp.emc.com/browse/MAG-222

related PRs:
https://github.com/RackHD/on-tasks/pull/55
https://github.com/RackHD/on-http/pull/28

### CODE REVIEW

**Comment by benbp** [comment]
:+1:

**Comment by tldavies** [comment]
test this please

**Comment by tldavies** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Pull request merged**
