### PR TITLE
Bump mocha timeout to 10000 to mitigate potential jenkins issues

### PR DESCRIPTION
**Pull request by benbp**
Proposing a potential way to address what could be jenkins timeout issues when loading modules in mocha "before" blocks.

@RackHD/corecommitters @tldavies @davidzuhn

### CODE REVIEW

**Comment by tldavies** [comment]
👎  This should try to be fixed via jenkins with lowering the node count for the build slave first.

**Comment by davidzuhn** [comment]
What do you mean by "lowering the node count for the build slave"?

**Comment by tldavies** [comment]
So the old build slave for 1.1 release only have 2 nodes. While the new build slave has 4. I would lower that count to 2 again. As that worked in the passed when we had timeouts in jenkins.

**Comment by davidzuhn** [comment]
Do you mean cpus?

**Comment by tldavies** [comment]
screen shot 2016-05-02 at 3 32 03 pm
The above photo shows 4 idle reduces it to 2.

**Comment by davidzuhn** [comment]
Most of the build failures have occurred when that build job was the only one running on the given node.

**Pull request closed without merging**
