### PR TITLE
Converting http response to json if valid json

### PR DESCRIPTION
**Pull request by nucklehead**
Signed-off-by: Bala Balakumaran <bala.balakumaran@dell.com>

When a `Task.Base.Rest` is is used in a graph, it adds the outputs in the context which can then be refereed by subsequent tasks as `context.restData.body` however this is always a string. 

This PR allows the **body** to be converted to JSON if it is a valid JSON.
That way one can refer to ex: `context.restData.body.token`

### CODE REVIEW

**Comment by mtannous** [comment]
@tannoa2 can you have a look at this

**Comment by keedya** [comment]
ok to test

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- LICENSE - package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- LICENSE - package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- LICENSE - package.json

**Pull request merged**
