### PR TITLE
[1.2.0-branch] locking version of apache-crypt to be 1.0.9 to fix on-core

### PR DESCRIPTION
**Pull request by tldavies**
This is the same PR to https://github.com/RackHD/on-core/pull/139 but for the release/1.2.0-branch

### CODE REVIEW

**Comment by tldavies** [comment]
@rolandpoulter @RackHD/corecommitters

**Comment by rolandpoulter** [comment]
👍

**Comment by VulpesArtificem** [comment]
👍

**Comment by DavidjohnBlodgett** [comment]
👍  :)

**Pull request merged**
