### PR TITLE
Fix lookup query atomicity and indexing. Update findAndModifyMongo da…

### PR DESCRIPTION
**Pull request by benbp**
…te modifiers

Resolves https://github.com/RackHD/RackHD/issues/121
Resolves https://github.com/RackHD/RackHD/issues/122

@RackHD/corecommitters @johren @heckj @tldavies

### CODE REVIEW

**Comment by benbp** [comment]
The key changes here are an update to the queries in the lookup model, as well as adding a compound index for lookups. I also took the opportunity to improve waterline date fields based on various mongo queries.

DO NOT MERGE. I'm realizing I still need to enforce index uniqueness, going to make those changes now.

**Comment by heckj** [comment]
@benbp do we have any unit tests or the like that can verify the schema validation out of this? (likely repeat now that you found the underlying code to tweak, but maybe useful?) and anything to validate the indices?

**Comment by benbp** [comment]
@heckj I could add a test to the functional tests RackHD/RackHD/tests that just looks at mongo indexes after starting the services, but that doesn't guarantee that they weren't created elsewhere. Any further granularity would require something like what is being discussed at https://groups.google.com/forum/#!topic/rackhd/KuGYxlJFk-0.

The schema validation is also tricky for a similar reason. We need to verify it against what comes out of a real database, which can't be done in unit test. But I could add a functional test to make a lookup API call with a conflicting IP which would test the regression.

**Comment by tldavies** [comment]
test this please

**Comment by benbp** [comment]
CC @keedya @hohene

**Comment by benbp** [comment]
@heckj digging into this, there's actually no good way to test this at all in the functional tests, because we don't expose this call currently in any testable part of the API.

**Comment by heckj** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by jlongever** [comment]
Was this merged without functional tests passing?

**Comment by zyoung51** [comment]
@jlongever on-http downstream unittests also fail with this change.  The waterline.lookups in start() is undefined.

**Comment by zyoung51** [comment]
A fix for on-http is here: https://github.com/RackHD/on-http/pull/177

**Comment by tldavies** [comment]
RackHD/on-http#177 has been merged to master

**Pull request merged**
