### PR TITLE
add vscode config into gitignore list

### PR DESCRIPTION
**Pull request by yyscamper**
Add vscode config file into gitignore list since I am using vscode for remote debugging, it is annoying to see it in "git status".

### CODE REVIEW

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by heckj** [comment]
@yyscamper you guys trying out VSCode for editing/debugging? How are you liking it?

**Comment by yyscamper** [comment]
@heckj : So far so good. Actually I only use VSCode for debugging, vim is still my favorite for code editing, sometimes I use VSCode for markdown. My experience for VSCode is it is very fast (comparing with WebStorm).

My case for using VSCode is for remote debugging, the code runs in a Linux VM, but I want to debug it in my Windows PC. I tried node-inspector + Chrome before, local debugging is good, but remote debugging often lack of response. VSCode had a feature to sync local & remote source code, so far the remote debugging works very good.

**Pull request merged**
