### PR TITLE
Update workflow mongo store queries for active states

### PR DESCRIPTION
**Pull request by rolandpoulter**
This fixes a bug with https://github.com/RackHD/on-http/pull/246 that causes workflows to never finish.

### CODE REVIEW

**Comment by heckj** [comment]
is this relevant to the 1.2 branch? i.e. if the PR in http was in that branch, let's get a copy of this PR made for the 1.2 branch as well please

:+1:

**Comment by rolandpoulter** [comment]
Will do. As soon as I get the unit tests to pass.

**Comment by rolandpoulter** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by rolandpoulter** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by tldavies** [comment]
@rolandpoulter Rebase on Master

**Comment by heckj** [comment]
:+1:

**Comment by rolandpoulter** [comment]
test this please

**Pull request merged**
