### PR TITLE
removed misplaced unique flag

### PR DESCRIPTION
**Pull request by VulpesArtificem**
fix for https://github.com/RackHD/RackHD/issues/228
@RackHD/corecommitters

### CODE REVIEW

**Comment by benbp** [comment]
👍 

FYI @hohene

**Comment by yyscamper** [comment]
:+1:

**Comment by derrickostertag** [comment]
@RackHD/corecommitters, @hohene Is there anything holding this merge?

**Comment by anhou** [comment]
before merging, let Jenkins pass. test this please

**Comment by yyscamper** [comment]
@derrickostertag , I see the unit-testing is failed as well, this also deserve a fix.

**Comment by yyscamper** [comment]
From the unit-test error, I believe this PR will fix it: https://github.com/RackHD/on-core/pull/139.

**Comment by hohene** [comment]
test this please

**Comment by tldavies** [comment]
@VulpesArtificem Rebase on master.

**Pull request merged**
