### PR TITLE
Update workflow mongo store queries for active states

### PR DESCRIPTION
**Pull request by rolandpoulter**
Same as https://github.com/RackHD/on-core/pull/136 but for 1.2 branch

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by rolandpoulter** [comment]
test this please

**Comment by tldavies** [comment]
@rolandpoulter Rebase on Master

**Comment by rolandpoulter** [comment]
Should this be rebased against the 1.2.0-branch?
@tldavies did your fix get merged into release/1.2.0-branch?

**Comment by jlongever** [comment]
+1

**Pull request merged**
