### PR TITLE
WIP test PR do not merge

### PR DESCRIPTION
**Pull request by geoff-reid**
Test PR do not merge!

### CODE REVIEW

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- LICENSE - package.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- test.js

**Comment by PengTian0** [comment]
test this please

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- test.js

**Pull request closed without merging**
