### PR TITLE
Fix redfish obm service constants

### PR DESCRIPTION
**Pull request by jlongever**
@RackHD/corecommitters @zyoung51 @geoff-reid @tannoa2 @keedya @uppalk1

### CODE REVIEW

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
Invite @iceiilin to review this PR as she first designs this constants table

**Comment by iceiilin** [comment]
@jlongever It seems in this PR you will allow "redfish obm setting" be put into nodes with type "enclosure". Will enclosure node has this redfish obm settings? I can't think of this hardware configuration, and only pdu obm setting from my understanding is suitable for enclosure node.

**Comment by jlongever** [comment]
@linlynn Yes, both enclosure (Redfish Chassis resource) and compute (Redfish Systems resource) support Redfish OBM settings.

**Comment by jlongever** [comment]
test this please

**Comment by tannoa2** [comment]
+1

**Pull request merged**
