### PR TITLE
removed refs to onRack

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@heckj @benbp 

Please do not merge, blocked...

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
@benbp could you review these changes... does this look like it will handle the OnRack backwards compatibility?

**Comment by DavidjohnBlodgett** [comment]
@benbp magic value sorted... thanks!

**Comment by jlongever** [comment]
test this please

**Comment by DavidjohnBlodgett** [comment]
@jlongever so afew of us poked at these failures yesterday and it looked (to us) to maybe be on-dhcp-proxy was not having npm install run and was causing missing dependencies~ thought I'd give you a heads up, if you were still trying to chase the errors down, maybe the info will help!

**Comment by jlongever** [comment]
@DavidjohnBlodgett: npm gets installed, the problem is one of the downstream dependent job fails because it cannot apply this PR's commit to it.   Not yet sure why it only happens with this PR.

**Comment by DavidjohnBlodgett** [comment]
@jlongever understood!

**Comment by jlongever** [comment]
test this please

**Comment by benbp** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
^^ unit test false negative.   How come the coverage dropped?
+1

**Comment by benbp** [comment]
Yeah it would be good to add a super quick/simple test for the configuration service.

**Comment by DavidjohnBlodgett** [comment]
@jlongever @benbp so not sure why coveralls looks like it's hug for me... but this last commit should fix any lingering issues with this PR.

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
@DavidjohnBlodgett looks good and Jenkins randomness resolved.  Can this be merged?

**Comment by DavidjohnBlodgett** [comment]
@jlongever yes please!

**Pull request merged**
