### PR TITLE
Update constants

### PR DESCRIPTION
**Pull request by jlongever**
Add node types constant
Add Redfish obm service definition
Add Redfish poller name

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

### CODE REVIEW

**Comment by zyoung51** [comment]
+1

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
teat this please

**Comment by heckj** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Pull request merged**
