### PR TITLE
Adds running to active states constant

### PR DESCRIPTION
**Pull request by rolandpoulter**
For ODR-593 and https://www.pivotaltracker.com/n/projects/1492888/stories/115448753

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
test this please

**Comment by heckj** [comment]
test this please

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by zyoung51** [comment]
test this please

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
