### PR TITLE
make the identifier property in the node unique, so when discovering …

### PR DESCRIPTION
**Pull request by tannoa2**
…usc nodes no duplicate will be created

### CODE REVIEW

**Comment by tannoa2** [comment]
PR depends on: RackHD/RackHD#585

**Comment by tannoa2** [comment]
@RackHD/corecommitters @RackHD/veyron

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
test this please

**Comment by anhou** [comment]
@tannoa2 I faced the same problem about on-tasks unittest failure, please rebase on-core codes

**Comment by panpan0000** [comment]
Please rebase your PR branch to latest master , otherwise, on-tasks unit-test will fail. (task-schema)

**Pull request closed without merging**
