### PR TITLE
issue#326: change the log level of using default configuration value from info to warning

### PR DESCRIPTION
**Pull request by yyscamper**
resolves https://github.com/RackHD/RackHD/issues/326

@heckj @RackHD/corecommitters

### CODE REVIEW

**Comment by heckj** [comment]
I'm totally good with this change - but is this warning even of value? Do we care when we a default value vs. a value set in a configuration file?

👍

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
@heckj : your concern makes sense, I agree the `warning` will be better than `debug`. The PR has been updated with your comment is addressed.

**Comment by cgx027** [comment]
:+1:

**Pull request merged**
