### PR TITLE
Set role attribute in roles collection to be a unique index

### PR DESCRIPTION
**Pull request by keedya**
@RackHD/corecommitters @brianparry @zyoung51 @jlongever @srinia6 @dalebremner @BillyAbildgaard

### CODE REVIEW

**Comment by keedya** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by panpan0000** [comment]
@changev , Latest Jenkins build for this PR is successful, 
http://rackhdci.lss.emc.com/job/on-core/867/
why it's still a red "X" ?

**Comment by changev** [comment]
This morning DeadLock occurs in Maglev-BRI-Test jobs, 

When I kill jobs , carelessly one commit-status-repair job was killed

http://rackhdci.lss.emc.com/job/Maglev-BRI-Test/job/on-core-prior/84/console

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
