### PR TITLE
Dockerfile refactor removes extra node_modules

### PR DESCRIPTION
**Pull request by rolandpoulter**
Removes extra copy of node_modules directory which reduces the size of the docker image.

### CODE REVIEW

**Comment by heckj** [comment]
+1

**Comment by zyoung51** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
+1

**Pull request merged**
