### PR TITLE
Add views constant and waterline model

### PR DESCRIPTION
**Pull request by brianparry**
This change adds a constant and waterline model needed for https://github.com/RackHD/on-http/pull/206

### CODE REVIEW

**Comment by brianparry** [comment]
@RackHD/corecommitters @srinia6 @geoff-reid @dalebremner @abildw

**Comment by zyoung51** [comment]
Did you want to change the name to ViewModelFactory rather than TemplateModelFactory?  Aside from that looks good.  +1

**Comment by brianparry** [comment]
@zyoung51 Yep - copy/paste error.

**Comment by benbp** [comment]
👍

**Comment by brianparry** [comment]
jenkins aborted, so test this please

**Pull request merged**
