### PR TITLE
log level reduction

### PR DESCRIPTION
**Pull request by heckj**
final pull request to resolve https://github.com/RackHD/RackHD/issues/34

**NOTE**: Requires all other PR's for log normalization in projects
using on-core to be merged prior to merging this PR. As I'm setting this
up, only https://github.com/RackHD/on-tasks/pull/95 remains to be merged
prior to this PR

### CODE REVIEW

**Comment by yyscamper** [comment]
@heckj : I see some "logger.deprecate" in code, now it's a special function compared with other log levels, Do you think we'd better move the deprecate to the levels table?

If add into levels table, seems the deprecate is different with "error, warn, ...", hard to determine its priority.
But the benefit is we can get uniform control over all logger behavior.

**Comment by heckj** [comment]
@yyscamper I think keeping `deprecate` as a special function is valuable and has merit as it is, rather than trying to shove it into a level list, that has semantically different meaning. `deprecate` specifically maps to a log level as well, so I view it as a useful convenience function that should be primarily for ourselves. I don't believe it violates any logging behaviour given that it's mapped to a specific log level and utilizes all the same underlying infrastructure

**Comment by yyscamper** [comment]
@heckj , I agree. :+1:

**Comment by anhou** [comment]
the enum number is '1.2, 4, 5 ,6', could you help keep it in sequential? to avoid when someone see these numbers, have the question "why skip 0 and 3"
:+1:  after modify to sequential numbers

**Comment by heckj** [comment]
@anhou updated to sequence the values linearly and remove the "gaps" from a straight up delete

**Comment by anhou** [comment]
:+1: 
https://github.com/RackHD/on-tasks/pull/95 has been merged, so I'll merge this PR

**Pull request merged**
