### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by josephgorse**

### CODE REVIEW

**Comment by panpan0000** [comment]
sorry, but on-taskgraph docker build will fail

**Comment by keedya** [comment]
@panpan0000 I see!!
I will fix or revert the changes

**Comment by changev** [comment]
@keedya  I'm fixing it

**Comment by keedya** [comment]
@changev 👍 Thanks!

**Comment by panpan0000** [comment]
Thank you @changev .
the detail has been recorded in https://rackhd.atlassian.net/browse/RAC-6092

**Pull request merged**
