### PR TITLE
Add string constant for SNMP sensor metric poller

### PR DESCRIPTION
**Pull request by zyoung51**

### CODE REVIEW

**Comment by benbp** [comment]
👍

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by zyoung51** [comment]
test this please

**Comment by PengTian1** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Pull request merged**
