### PR TITLE
added rack node type and contains relationtype

### PR DESCRIPTION
**Pull request by VulpesArtificem**
part of https://github.com/RackHD/RackHD/wiki/proposal-passively-add-remove-a-rack-node 
adds the contains/containedBy relations
supports https://github.com/RackHD/on-http/pull/432
@RackHD/corecommitters  @pscharla

### CODE REVIEW

**Comment by pscharla** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by pscharla** [comment]
@VulpesArtificem This PR needs to be merged for the above referenced on-http PR to pass checks, right?

@RackHD/corecommitters this PR is related to functionality that we are attempting to get in this sprint for 2.1.0 OnRack release. Please review and merge ASAP.  Thanks and thank you @anhou for already reviewing.

**Comment by DavidjohnBlodgett** [comment]
👍

**Comment by heckj** [comment]
👍

**Comment by tldavies** [comment]
👍

**Pull request merged**
