### PR TITLE
Always return promise when validating arp cache

### PR DESCRIPTION
**Pull request by jlongever**
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

### CODE REVIEW

**Comment by zyoung51** [comment]
+1, test this please

**Comment by heckj** [comment]
👍

**Comment by heckj** [comment]
@RackHD/corecommitters please review

**Comment by heckj** [comment]
related to https://github.com/RackHD/RackHD/issues/225

**Comment by benbp** [comment]
👍

**Comment by yyscamper** [comment]
jenkins: test this please

**Pull request merged**
